### PR TITLE
Provide CuDNN support as well as publish mvn repo on github

### PR DESCRIPTION
**Pull request by niketanpansare**
This PR attempts to address two problems:
1) When a project wants to provide "optional support" for JCuda and
related libraries. In this case, not all the developers on the project
may have Nvidia GPU or want to use CUDA. So, the project can include mavenized cuda
in provided scope:
``` python
        <dependency>
			<groupId>org.mystic</groupId>
			<artifactId>mavenized-jcuda</artifactId>
			<version>0.1.2</version>
			<scope>provided</scope>
		</dependency>
```

2) Not requiring hosting a local maven repository, so that user can use
following in their pom file:
``` python
    <repositories>
		<repository>
          <id>central</id>
          <url>https://repo1.maven.org/maven2</url>
          <releases>
            <enabled>true</enabled>
          </releases>
        </repository>
	    <repository>
	        <id>mavenized-jcuda-mvn-repo</id>
<url>https://raw.github.com/MysterionRise/mavenized-jcuda/mvn-repo/</url>
	        <snapshots>
	            <enabled>true</enabled>
	            <updatePolicy>always</updatePolicy>
	        </snapshots>
	    </repository>
	</repositories>
```
Additionally, in this PR, I have added CuDNN support and created a new
profile that deploys the jar on github.

Following steps will deploy the jar on github, so that other projects
can include mavenized-jcuda as its build dependency:
Step 1: Create settings.xml in .m2 folder
``` python
<!-- NOTE: MAKE SURE THAT settings.xml IS NOT WORLD READABLE! -->
<settings>
  <servers>
    <server>
      <id>github</id>
      <username>YOUR-USERNAME</username>
      <password>YOUR-PASSWORD</password>
    </server>
  </servers>
</settings>
```

Step 2: Compile with deploy-jar profile
Assuming that user is running on windows, then to deploy the jar:
``` python
mvn clean package -P deploy-jar,!windows-x86_64
mvn clean deploy -P deploy-jar,!windows-x86_64
```

### CODE REVIEW

**Comment by MysterionRise** [comment]
Hi, Niketan.

I will try to take a look into PR during the day, so far I could say thanks for new ideas to improve the project.

**Comment by niketanpansare** [comment]
Thanks @MysterionRise I appreciate it :)

There are two possible ways to handle the first problem ("provided" scope):
1. Create one fat jar with jcu*.jar dependencies (done in this PR). If you chose to go with this option, I would recommend keeping the version numbers consistent with JCuda.
2. Publish jcu*.jar in  https://github.com/MysterionRise/mavenized-jcuda/mvn-repo. However, I could not figure out an easy way to do that. In this case, please delete dep.xml and mvn assembly part in pom.

Thanks again for taking time to review the PR :)

**Comment by MysterionRise** [comment]
1. Fat jar sounds like a stable solution to me, at least it should work

2. Publishing to mvn-repo, that's a new thing to me, I never did it before. Is it feasible?

**Comment by niketanpansare** [comment]
Yes, mvn-repo works. As an example, I created a mvn-repo on the fork. To verify, please include following in java project that uses JCuda:
``` python
<repositories>
		<repository>
          <id>central</id>
          <url>https://repo1.maven.org/maven2</url>
          <releases>
            <enabled>true</enabled>
          </releases>
        </repository>
	    <repository>
	        <id>mavenized-jcuda-mvn-repo</id>
	        <url>https://raw.github.com/niketanpansare/mavenized-jcuda/mvn-repo/</url>
	        <snapshots>
	            <enabled>true</enabled>
	            <updatePolicy>always</updatePolicy>
	        </snapshots>
	    </repository>
	</repositories>
....
<dependencies>	
		<dependency>
			<groupId>org.mystic</groupId>
			<artifactId>mavenized-jcuda</artifactId>
			<version>0.1.2</version>
			<scope>provided</scope>
		</dependency>
</dependencies>
```

Are you OK with keeping the version number of mavenized-jcuda consistent with JCuda ?

**Comment by niketanpansare** [comment]
Also, please note that when you want publish older jars, you may have to comment out the dependency that older jcuda didn't contain. For example:
``` python
# Keeping jcuda-version and mavenized-jcuda version to 0.7.5b
mvn clean package -P deploy-jar,!windows-x86_64
mvn clean deploy -P deploy-jar,!windows-x86_64

# Keeping jcuda-version and mavenized-jcuda version to 0.7.5
# Comment out jcudnn in pom.xml
mvn clean package -P deploy-jar,!windows-x86_64
mvn clean deploy -P deploy-jar,!windows-x86_64

....
# Keeping jcuda-version and mavenized-jcuda version to 0.7.5
# Comment out jcusolver in pom.xml
and so on
```
The above commands to deploy all the versions of mavenized-jcuda that are consistent which jcuda versions :)

**Comment by niketanpansare** [comment]
Thanks @MysterionRise ... I appreciate you merging the PR. Can you please deploy the jars so that external projects can use your `mvn-repo` branch as their mvn repository ? 

Step 1: Create settings.xml in .m2 folder
``` python
<!-- NOTE: MAKE SURE THAT settings.xml IS NOT WORLD READABLE! -->
<settings>
  <servers>
    <server>
      <id>github</id>
      <username>YOUR-USERNAME</username>
      <password>YOUR-PASSWORD</password>
    </server>
  </servers>
</settings>
```

Step 2: Compile with deploy-jar profile
Assuming that you are running on windows:
``` python
# Keeping jcuda-version and mavenized-jcuda version to 0.7.5b
mvn clean package -P deploy-jar,!windows-x86_64
mvn clean deploy -P deploy-jar,!windows-x86_64

# Keeping jcuda-version and mavenized-jcuda version to 0.7.5
# Comment out jcudnn in pom.xml
mvn clean package -P deploy-jar,!windows-x86_64
mvn clean deploy -P deploy-jar,!windows-x86_64

....
# Keeping jcuda-version and mavenized-jcuda version to 0.7.5
# Comment out jcusolver in pom.xml
and so on
```

**Comment by MysterionRise** [comment]
Yes, I'm currently doing stuff, to make old solution still work (also add 0.7.5b for Linux and PPC, which was missing)

I am looking forward to try deployment to external repo.

**Comment by MysterionRise** [comment]
Okay. I did a quick deploy of jcuda lib. Now I've got, that I need some smart routine to publish stuff one by one without manually changing pom.xml.

Will continue work on it later.

**Comment by niketanpansare** [comment]
Thanks @MysterionRise :+1: 

As an FYI, I have added references to mavenized-jcuda to one of the project that I am contributing to:
* https://github.com/niketanpansare/incubator-systemml/blob/1a52bd8908773593fb8b240b38ed0e81a33ebb3f/pom.xml#L85
* https://github.com/niketanpansare/incubator-systemml/blob/1a52bd8908773593fb8b240b38ed0e81a33ebb3f/docs/devdocs/gpu-backend.md#setup-instructions-for-jcudacontext

**Pull request merged**
