### PR TITLE
add support for 0.7.0a native libraries for ppc64le #8

### PR DESCRIPTION
**Pull request by kiszk**
add native libraries for ppc64le

### CODE REVIEW

**Comment by MysterionRise** [comment]
Just curious, did you use my script for adding to maven repo?

**Comment by kiszk** [comment]
I did not use your script. Later, I will update your script and use it, then will create another pull request.
Do it make sense?

**Comment by MysterionRise** [comment]
So, you put it manually? No, I could update everything myself, no worries.

2015-10-09 13:44 GMT+02:00 Kazuaki Ishizaki <notifications@github.com>:

**Comment by kiszk** [comment]
Yes, i did it manually.

**Pull request merged**
